anchor_version = "0.26.0"
solana_version = "1.14.10"

[programs.localnet]
voter_stake_registry = "VotEn9AWwTFtJPJSMV5F9jsMY6QwWM5qn3XP9PATGW7"

[programs.devnet]
voter_stake_registry = "VotEn9AWwTFtJPJSMV5F9jsMY6QwWM5qn3XP9PATGW7"

[programs.mainnet]
voter_stake_registry = "VotEn9AWwTFtJPJSMV5F9jsMY6QwWM5qn3XP9PATGW7"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
